function(gather_symbols TARGET)
    get_target_property(SOURCES ${TARGET} SOURCES)
    foreach(SRC ${SOURCES})
        if(NOT SRC STREQUAL "")
            get_filename_component(EXT ${SRC} EXT)
            if(EXT STREQUAL ".h" OR EXT STREQUAL ".hpp")
                set(HEADERS ${HEADERS} ${SRC})
            endif()
        endif()
    endforeach()
    set_target_properties(${TARGET} PROPERTIES HEADERS ${HEADERS})
endfunction()